# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaccount',
            name='sZip',
            field=models.IntegerField(verbose_name='Zip'),
        ),
    ]
